### ISSUE TITLE
API Documentation Request!

### ISSUE THREAD

**Issue by deejinng** [ottoh3x/animex-lab#1]
Not really an issue... I understand the web app is still under development.

The API you made (I saw the url while exploring the codebase) I will appreciate if you can make a simple Documentation of each endpoints, I'm a React/Nextjs fan and I'd love to make something practical with it.

Happy Coding.

**Comment by ottoh3x** [comment]
Absolutely. Btw i forgot that i made this repo public my bad.

**Comment by deejinng** [comment]
Ohhh... I'd love to connect with you what platform do you often use?

**Comment by ottoh3x** [comment]
discord => .ottomatic.

**Comment by deejinng** [comment]
Alright... will leave a message soon.
